// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGaDoTC0723fnln8ZI3Bzc5A6vBgJWsvk',
    appId: '1:83764059549:web:149c7c11301a49ec81e374',
    messagingSenderId: '83764059549',
    projectId: 'fir-21312071',
    authDomain: 'fir-21312071.firebaseapp.com',
    databaseURL: 'https://fir-21312071-default-rtdb.firebaseio.com',
    storageBucket: 'fir-21312071.appspot.com',
    measurementId: 'G-16EQJ7300J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-sfyTtQlabCaFkoChZmHE-owoG75z5oU',
    appId: '1:83764059549:android:de87e7ee2c6a5ea381e374',
    messagingSenderId: '83764059549',
    projectId: 'fir-21312071',
    databaseURL: 'https://fir-21312071-default-rtdb.firebaseio.com',
    storageBucket: 'fir-21312071.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLc247cKIM4u_xO1oUiIVCcZRjuZIcGdk',
    appId: '1:83764059549:ios:9f6a6e1bbc2364ba81e374',
    messagingSenderId: '83764059549',
    projectId: 'fir-21312071',
    databaseURL: 'https://fir-21312071-default-rtdb.firebaseio.com',
    storageBucket: 'fir-21312071.appspot.com',
    iosClientId: '83764059549-vs0r3f0pct7n9arf6oe6hif0flsis564.apps.googleusercontent.com',
    iosBundleId: 'com.ifgabsp.projectGet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLc247cKIM4u_xO1oUiIVCcZRjuZIcGdk',
    appId: '1:83764059549:ios:3d2a5b0c85a04cdd81e374',
    messagingSenderId: '83764059549',
    projectId: 'fir-21312071',
    databaseURL: 'https://fir-21312071-default-rtdb.firebaseio.com',
    storageBucket: 'fir-21312071.appspot.com',
    iosClientId: '83764059549-vthbn5fhh0lg9ek9rqeiobpqmc1ertjp.apps.googleusercontent.com',
    iosBundleId: 'com.ifgabsp.projectGet.RunnerTests',
  );
}
